### PR TITLE
Optionally run pip3 install when the file is present.

### PR DESCRIPTION
**Pull request by oscarnevarezleal**
Optionally run pip3 install when the file is present.

### CODE REVIEW

**Comment by ScottBrenner** [comment]
Is this to address an error you've experienced?

**Comment by oscarnevarezleal** [comment]
Hello, apologies for the delay in my response.  

I don't recall exactly the details of my experience, but I do remember that the action was looking for _requirements.txt_ on my project (NodeJS)

**Comment by ScottBrenner** [comment]
Got it - I've only tested this Action with Python, not Node.js. Were you able to use the Action with Node.js after making the changes here?

**Comment by oscarnevarezleal** [comment]
> Got it - I've only tested this Action with Python, not Node.js. Were you able to use the Action with Node.js after making the changes here?

I did, I ran _cdk synth_

**Review by ScottBrenner — APPROVED** [review]
Awesome, guess this adds support for Node.js then! Could you also update the line "Currently supports CDK apps created with Python" in  https://github.com/ScottBrenner/aws-cdk-action/blob/master/README.md#github-action-for-aws-cdk  ?

**Pull request merged**
